TailorApp.Web/Controllers/Rent/RentEntriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TailorApp.Application.Services;
using TailorApp.Domain.Entities;
using TailorApp.Domain.Entities.InventoryModel;
using TailorApp.Domain.Entities.SalesModule;
using TailorApp.Infrastructure.Data;
using r = TailorApp.Domain.Entities.RentModel;

namespace TailorApp.Web.Controllers.Rent
{
    [Authorize]
    public class RentEntriesController : Controller
    {
        private readonly IRentService _rentService;
        private readonly ICustomerService _customerService;
        private readonly IStockService _stockService;
        private readonly IIncomeService _incomeService;

        public RentEntriesController(IRentService rentService,
            ICustomerService customerService,
            IStockService stockService,
            IIncomeService incomeService)
        {
            _rentService = rentService;
            _customerService = customerService;
            _stockService = stockService;
            _incomeService = incomeService;
            
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            SelectList customerSelectList = await _customerService.GetSelectListAsync();
            ViewBag.CustomerID = customerSelectList;

            var stocks = await _stockService.GetListByCategoryAsync(CategoryType.Rent);

            return View(stocks);
        }
        
        [HttpPost]
        public async Task<JsonResult> SerializeFormData(IFormCollection _collection)
        {
            if (_collection != null)
            {
                string[] _stockID, _qty, _rate, _amt;
                //for rentDetail
                _stockID = _collection["StockID"].ToString().Split(',');
                
                _qty = _collection["Qty"].ToString().Split(',');
                _rate = _collection["Rate"].ToString().Split(',');
                _amt = _collection["Amount"].ToString().Split(',');
                string _remarks = _collection["Remarks"].ToString();
                var _return = Convert.ToDateTime(_collection["ReturnDate"]);
                int _customer = Convert.ToInt32(_collection["customers"]);
                //for rent
                decimal _total = Convert.ToDecimal(_collection["Total"]);
                decimal _discount = Convert.ToDecimal(_collection["Discount"]);
                decimal _grandTotal = Convert.ToDecimal(_collection["GrandTotal"]);
                decimal _advancePayment = Convert.ToDecimal(_collection["AdvancePayment"]);
          


                r.Rent _rent = new r.Rent()
                {
                    RentDate = DateTime.Now,
                    ReturnDate = _return,
                    Amount = _total,
                    Discount = _discount,
                    GrandTotal = _grandTotal,
                    AdvancePayment = _advancePayment,
                    Paid=0,
                    Remarks = _remarks,
                    CustomerID =_customer
                };
                _rent.IsPaid= (_rent.AdvancePayment == _rent.GrandTotal) ?  true : false;
                if (_rent.IsPaid) _rent.Paid = _rent.GrandTotal;

                int count = _stockID.Count();
                List<r.RentDetail> rentDetails = new List<r.RentDetail>();
                for (int i = 0; i < count; i++)
                {
                    r.RentDetail _rentItem = new r.RentDetail();

                    _rentItem.StockID = Convert.ToInt32(_stockID[i]);
                    _rentItem.Rate = Convert.ToDecimal(_rate[i]);
                    _rentItem.Quantity = Convert.ToInt32(_qty[i]);
                    _rentItem.Amount = Convert.ToDecimal(_amt[i]);
                    _rentItem.ReturnQuantity = _rentItem.Quantity;
                    rentDetails.Add(_rentItem);
                    
                }
                _rent.RentDetails = rentDetails;
                await _rentService.CreateAsync(_rent);

                //update stock
                List<Stock> stocks = new List<Stock>();
                for (int i = 0, y = _stockID.Count(); i < y; i++)
                {
                    int getStockID = Convert.ToInt32(_stockID[i]);
                    int getQty = Convert.ToInt32(_qty[i]);
                    var stock =await _stockService.FindByIdAsync(getStockID);
                    stock.Quantity = stock.Quantity - getQty;
                    stocks.Add(stock);
                }
                await _stockService.UpdateStockListAsync(stocks);

                //insert income
                Income income = new Income()
                {
                    Date = DateTime.Now,
                    RentID = _rent.RentID,
                    Name = "Rent",
                    Description = "Advanced payment " + _advancePayment + "TK/=",
                    Price = 0
                };
                await _incomeService.CreateAsync(income);

                return Json(_rent.RentID);

            }
            return Json("null");
        }


       
    }
}

TailorApp.Web/Controllers/Rent/RentReturnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TailorApp.Application.Dtos.DataTableDtos;
using TailorApp.Application.Services;
using TailorApp.Domain.Entities;
using TailorApp.Domain.Entities.InventoryModel;
using TailorApp.Domain.Entities.RentModel;
using TailorApp.Infrastructure.Data;
using r = TailorApp.Domain.Entities.RentModel;

namespace TailorApp.Web.Controllers.Rent
{
    public class RentReturnController : Controller
    {
        private readonly IRentReturnService _rentReturnService;
        private readonly IRentService _rentService;
        private readonly IStockService _stockService;
        private readonly IIncomeService _incomeService;
        public RentReturnController(IRentReturnService rentReturnService,
            IRentService rentService,
            IStockService stockService,
            IIncomeService incomeService)
        {
            _rentReturnService = rentReturnService;
            _rentService = rentService;
            _stockService = stockService;
            _incomeService = incomeService;
        }
        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var rents = await _rentReturnService.GetListAsync();
            return View(rents);
        }
        [Authorize]
        [HttpPost]
        public async Task<JsonResult> LoadRentReturnList([FromBody] DataTableDto dataTableDto)
        {
            object dataTable = await _rentReturnService.GetDataTableAsync(dataTableDto);
            return Json(dataTable);
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpGet]
        public async Task<ActionResult> ReturnDetails(int id)
        {
            var returnDetails = await _rentReturnService.FindByIdAsync(id);
            return PartialView(returnDetails);
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpGet]
        public async Task<IActionResult> Returns(int id)
        {
            r.Rent model = await _rentService.FindByIdAsync(id);
          
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpPost]
        public async Task<JsonResult> ReturnItems(IFormCollection coll)
        {
            bool status = true;
           
            List<r.RentReturnDetail> rentReturnDetails = new List<r.RentReturnDetail>();
            var rentDetail = new RentDetail();
            var counter = Convert.ToInt32(coll["counter"]);

            //attributes required for RentReturn
            decimal total = Convert.ToDecimal(coll["SubTotal"]);
            decimal discount = Convert.ToDecimal(coll["Discount"]);
            decimal netTotal = Convert.ToDecimal(coll["NetTotal"]);
            int rentID = Convert.ToInt32(coll["RentID"]);
            

            //populating through each of the occurance of the ReturnedItems
            for (int i = 1; i <= counter; i++)
            {
                var value = coll["Qty_" + i];
                if (!string.IsNullOrEmpty(value) && value != "0")
                {
                    r.RentReturnDetail rentReturnDetail = new r.RentReturnDetail
                    {
                        StockID = Convert.ToInt32(coll["StockID_" + i]),
                        Quantity = Convert.ToInt32(coll["Qty_" + i]),
                        Rate = Convert.ToDecimal(coll["Rate_" + i]),
                        Amount = Convert.ToDecimal(coll["Amount_" + i])
                    };
                    int rentDetailID = Convert.ToInt32(coll["RentDetailID_"+i]);
                    rentDetail =await _rentService.FindDetailByIdAsync(rentDetailID);
                    rentDetail.ReturnQuantity -= Convert.ToInt32(coll["Qty_" + i]);
                    rentReturnDetails.Add(rentReturnDetail);
                }
            }
            if (rentDetail.ReturnQuantity >= 0)
            {
                foreach (var item in rentReturnDetails)
                {
                    Stock stock = new Stock();
                    stock =await _stockService.FindByIdAsync(item.StockID);
                    stock.Quantity += item.Quantity;

                }

                //populating rent Return
                r.RentReturn rentReturn = new r.RentReturn
                {
                    RentID = rentID,
                    Subtotal = total,
                    Discount = discount,
                    NetTotal = netTotal,
                    RentReturnDetails = rentReturnDetails,
                    Description = "n/a",
                    ReturnedDate = DateTime.Today
                };
                await _rentReturnService.CreateAsync(rentReturn);

                //update rent
                var rent =await _rentService.FindByIdAsync(rentID);
                rent.Paid += netTotal;
                rent.IsPaid = (rent.Paid == rent.GrandTotal) ? true : false;

                await _rentService.UpdateAsync(rent);
                
                //update income
                var income =await _incomeService.GetByRentId(rent.RentID);
                income.Price += rent.Paid;
                await _incomeService.UpdateAsync(income);
                

                return new JsonResult(new { Data = new { status = status, message = "Order Added Successfully" } });
            }
            status = false;
            return new JsonResult(new { Data = new { status = status, message = "Error !" } });

        }


    }

}

TailorApp.Web/Controllers/Rent/RentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TailorApp.Application.Dtos.DataTableDtos;
using TailorApp.Application.Services;
using TailorApp.Domain.Entities;
using TailorApp.Infrastructure.Data;
using p = TailorApp.Domain.Entities.RentModel;

namespace TailorApp.Web.Controllers.Rent
{
    [Authorize]
    public class RentsController : Controller
    {
        private readonly IRentService _rentService;

        public RentsController(IRentService rentService)
        {
            _rentService = rentService;
        }

        [HttpGet]
        public IActionResult Index()
        { 
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> LoadRentList([FromBody] DataTableDto dataTableDto)
        {
            object dataTable = await _rentService.GetDataTableAsync(dataTableDto);
            return Json(dataTable);
        }



    }
}

TailorApp.Web/Views/Rents/Index.cshtml
@model IEnumerable<TailorApp.Domain.Entities.RentModel.Rent>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .dataTables_filter {
        display: none;
    }
</style>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-block">
                <div class="col-lg-12">
                    <b><i class="ti-tag"></i> <span><b>Rent List</b></span></b>
                    <a class="btn btn-success" style="margin-bottom:12px;float:right;" href="/RentEntries/Index"><i class="ti-plus"></i>Create New</a>
                </div>
                <br />
                <hr />
                <div class="dt-responsive table-responsive">
                    <table class="table table-striped table-bordered nowrap" id="rentTable">
                        <thead>

                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.RentID)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RentDate)
                                </th>
                                <th>

                                    @Html.DisplayNameFor(model => model.ReturnDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Amount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Discount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.GrandTotal)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Customer)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.AdvancePayment)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Paid)
                                </th>
                                <th>Status</th>
                                <th>Returned</th>
                            </tr>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.RentID)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RentDate)
                                </th>
                                <th>

                                    @Html.DisplayNameFor(model => model.ReturnDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Amount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Discount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.GrandTotal)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Customer)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.AdvancePayment)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Paid)
                                </th>
                                <th>Status</th>
                                <th>Returned</th>
                            </tr>
                        </thead>
                       
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="~/js/Popup.js"></script>
    <script>

        $(document).ready(function () {

            jQuery('#rentTable thead tr:eq(0) th:not(:last,:first,:nth-child(11))').each(function () {
                    var title = jQuery(this).text();
                    jQuery(this).html('<input class="form-control" type="text" placeholder="Search ' + title + '" />');
                });

            var rentTable = $("#rentTable").DataTable({
                'processing': true,
                'serverSide': true,
                "order": [[0, 'desc']],
                'ajax': {
                    'url': '@Url.Action("LoadRentList", "Rents")',
                    'method': 'POST',
                    'contentType': 'application/json',
                    'data': function (d) {
                        return JSON.stringify(d);
                    }
                },
                "lengthMenu": [[10, 15], [10, 15]],
                "lengthChange": true,
                "searching": true,
                "scrollX": true,
                //fixedColumns: {
                //    leftColumns: 1,
                //    rightColumns: 1
                //},

                'columns': [
                    {
                        data: "rentID", name: "RentID",
                    },
                    { data: "rentDate", name: "RentDate", },
                    {
                        data: "returnDate", name: "returnDate", searchable: false,
                        render: function (data, type, row, meta) {
                            if (row.IsDateOver == "true" && row.IsEqual=="true")
                                return '<label style="color:red;">' + row.returnDate + '</label>'
                            else
                                return '<label>' + row.returnDate+'</label>'

                        },
                    },

                    { data: "amount", name: "Amount", },
                    { data: "discount", name: "Discount",},
                    { data: "grandTotal", name: "GrandTotal",},
                    { data: "customer", name: "Customer", },
                    { data: "advancePayment", name: "advancePayment", },
                    {
                        data: "paid", name: "Paid",
                        render: function (data, type, row, meta) {
                            if (row.paid == "0")
                                return '<label> - </label>'
                            else
                                return '<label>' + row.paid + '</label>'

                        },
                    },

                    {
                        data: "isPaid", name: "isPaid",
                        render: function (data, type, row, meta) {
                            if (row.isPaid == "true")
                                return '<a href="/RentReturn/Returns/'+row.rentID+'" style="padding: 3px 10px 3px 10px; background-color:green " class="badge" readonly>Paid</a>'
                            else
                                return '<a href="/RentReturn/Returns/+'+row.rentID+'" style="padding: 3px 10px 3px 10px; background-color:red " class="badge" readonly>Due</a>'

                        },
                    },
                    {
                        data: "orderID", name: "orderID",
                        render: function (data, type, row, meta) {
                            return row.returned +' / '+ row.total

                        }
                    },
                ]
            });

            // Individual Column Searching In case of Some Fixed Column
            jQuery(document).on('focusout', '#rentTable_wrapper thead input[type="text"]', function () {
                rentTable.column(jQuery(this).parent().index() + ':visible')
                    .search(this.value)
                    .draw();
            });


            // Select List filtering

            jQuery(rentTable.table().container()).on('change', 'thead select', function () {
                console.log(this.value);
                rentTable.column(jQuery(this).parent().index() + ':visible')
                    .search(this.value)
                    .draw();
            });
        });

    </script>

}